### ISSUE TITLE
Privilege for using admin chat

### ISSUE THREAD

**Issue by Razish** [Razish/japp#192]

**Comment by EpicLoyd** [comment]
is it really necessary? players can use admin chat to report abuse and that message will be highlighted

**Comment by Razish** [comment]
Indeed, I think this was a requested feature though.
In my opinion admin chat is a special utility to be used as you described. If admins/clan members want to have their unique chatroom, they can start their own channel and talk there.

**Comment by Morabis** [comment]
If you mean the current admin chat by a team chat mode it is necessary as it can be used by clients not having ja++ while the channels can be used with ja++ client only as I know.
