### ISSUE TITLE
Missing grapple animations

### ISSUE THREAD

**Issue by Razish** [Razish/japp#199]

**Comment by Dexter4637** [comment]
Any chance for fixing that?

**Comment by ensiform** [comment]
I would think they could be if they are just base anims.

**Comment by EpicLoyd** [comment]
Speed jump: w+attack+space (force speed enabled)

**Comment by ensiform** [comment]
The crappy ja+ implementation from sp? Lol please no.

**Comment by Razish** [comment]
People want the _option_ for JA+ compatibility. It won't be on by default, but it should match.

**Comment by Razish** [comment]
Fixed in 402c4a2
