### ISSUE TITLE
Fix: g_weaponDisable still spawning ammo

### ISSUE THREAD

**Issue by Razish** [Razish/japp#223]
?

**Comment by EpicLoyd** [comment]
Just checked it... ammo spawning only for enabled weapons  :\

**Comment by ensiform** [comment]
Ammo spawns if you don't have it set specifically to "Saber only"

**Comment by Razish** [comment]
Pretty sure it was a bug report I got from someone else, so I didn't look into it.
basejka behaviour sounds like the correct way to do it - multiple weapons use the same ammo type, and that's a pain to check for.

**Comment by videoP** [comment]
this seems to have worked for me, barely tested though
https://github.com/videoP/jaPRO/commit/f2374ebe64627d907f24f5f1ed0872f250a030c0

**Comment by Razish** [comment]
ref #395 which changed g_weaponDisable/HasSetSaberOnly behaviour to only consider usable, projectile/ammo-consuming weapons (excluding melee, saber, stun baton etc)

Leaving this open until the per-AMMO_* removal is added.
