### ISSUE TITLE
Fix: Weapon duel not giving ammo

### ISSUE THREAD

**Issue by Razish** [Razish/japp#237]

**Comment by EpicLoyd** [comment]
wil it global option for all weapons or for each weapon?

**Comment by EpicLoyd** [comment]
Fixed in b6b18b432af177b5c2d681d24fcb631bbd186af6

**Comment by ensiform** [comment]
There will be bugs with this.  The client doesn't think it has infinite ammo so if you had no ammo you won't be able to switch to it.  You also might get no ammo events predicted on the client if you spam a high ROF gun with low ammo Count before entering a duel.

**Comment by Razish** [comment]
b6b18b4 only avoids draining ammo. It doesn't give any ammo, meaning it's possible to enter a duel with a weapon you don't have ammo for.
