### ISSUE TITLE
Player freezing in lua.

### ISSUE THREAD

**Issue by YogSoth** [Razish/japp#266]
Sometimes i need to freeze players in mya lua scripts, so i am using EFlags2.HELD_BY_MONSTER, which is too buggy and causes lots of problems. Can you add lua freeze function similiar to the removed /amfreeze cmd?

**Comment by EpicLoyd** [comment]
Can be done in lua

**Comment by EpicLoyd** [comment]
something like this:

freezed = {}

local function freeze(ply,args)
ply = GetPlayer(args[1])
freezed[ply] = ply.posititon
end

local function checkfreeze()
for k,v in pairs(freezed) do
 k.position = v
end
end

AddListener('JPLUA_EVENT_RUNFRAME', checkfreeze)
AddClientCommand('amfreeze', freeze)

**Comment by Razish** [comment]
Better yet, there should now be an ability to control the same variable that `amfreeze` uses with the Player metatable.

**Comment by EpicLoyd** [comment]
yeah, but amfreeze deprecated and all functions replaced with amsleep :\
