### ISSUE TITLE
Stop amkiss with force push gencmd

### ISSUE THREAD

**Issue by Paullik74** [Razish/japp#268]
solved - another "bug" in my third comment
(https://github.com/Razish/japp/issues/268#issuecomment-65269639)

      Hello,
      first I'm sorry for my bad english.

     Command /amkiss do not work correctly. When I use it, something happened but not the kiss :D.

      Screen:
      http://cloud-2.steampowered.com/ugc/545263034545166591/57640F081012DBDB8AED1E16A1C5A076148CAF4B/
      http://cloud-4.steampowered.com/ugc/545263034545168105/4A7874006101C6C3B771C506DAB710FC5484E665/

     Sometimes that player/bot, who/which you use on do not stop attacking you, simple can still moving while command /amkiss is proceeds. Not me, but the other guy yes.

     Hope you will understand what I want to say :-).

     EDIt:
     server - latest JA++, Linux 32bit

    -  filelist in /japlus
           - jampgamei386.so, sh_animations.pk3, sh_lua.pk3, server configs

    -  filelist in /base:
           - assets0-3, jampgamei386.so, sh_animations.pk3, sh_lua.pk3

     I was trying copy sh_animations.pk3 to base, but nothing changed.

     my client - latest JA++, Windows

     -  filelist /japlus:
           - cgamex86.dll, cl_assets.pk3, cl_bins_win32.pk3, jampconfig.cfg, sh_animations.pk3, sh_lua.pk3, uix86.dll

     -   filelist /base:
           - assets0-3.pk3, jaconfig.cfg, jampconfig.cfg, sh_animations.pk3

**Comment by Razish** [comment]
Fair enough, updated title + status.

**Comment by Razish** [comment]
Added in 8fcec6f2bfc2ae10e5890d386bc5dbe4f74d5849
