### ISSUE TITLE
Fix: Grip in rolling event.

### ISSUE THREAD

**Issue by miguelsotobaez** [Razish/japp#275]
Needed in full force duel like JA+

**Comment by videoP** [comment]
can be cleaned up but this works for me, replacing the standard weapontime check
https://github.com/videoP/jaPRO/blob/6acd1473d8edda39dbfd260d4a3f2b3f74cf6f2c/codemp/game/w_force.c#L1407-L1421

**Comment by Razish** [comment]
Woop, this was fixed in 3e16bf9 :)
