### ISSUE TITLE
Duel buggy

### ISSUE THREAD

**Issue by Dexter4637** [Razish/japp#299]
U cant take damage while you are duelling with other players/bots

**Comment by ensiform** [comment]
Related to 3e79aec44edf5649b7a1ebcac4b519c3b5e70680 ?

**Comment by Dexter4637** [comment]
Yes maybe, even when you have "japp_chatprotection 0". U cant take dmg

**Comment by EpicLoyd** [comment]
Strange... Cannot check this, lost access to computer

**Comment by EpicLoyd** [comment]
Found problem and how to fix it, but unsure when i can commit it
