### ISSUE TITLE
new weapon system? 

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#302]
Totaly breaks compatiblity, but it might be cool
Desc: could add new weapons, just create ( json ) file and put it in /ext_data/weapons. In files you should describe: name of weapon, model of course, firing effects etc...
Could we do this, without editing engine?

**Comment by Razish** [comment]
Nope, you'd need to be able to network more data across.

**Comment by ensiform** [comment]
Those ext data files aren't even for multiplayer.

**Comment by EpicLoyd** [comment]
was an example :D
