### ISSUE TITLE
Can't download binaries from official page

### ISSUE THREAD

**Issue by sudge** [Razish/japp#314]
From here http://japp.jkhub.org/dl/cl_bins_win32.pk3 just getting the http://i6.5cm.ru/i/mWRn.png 404 error.

**Comment by ensiform** [comment]
I think downloads have been broken for a while now.

@Razish ?

**Comment by Razish** [comment]
Yeah, Windows builds haven't been updated. I've been extremely busy.
There's a note on the main page saying that the site is under maintenance and some download links may not work.

**Comment by Razish** [comment]
Should be all fixed now.
