### ISSUE TITLE
C++ Wrapper for lua

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#318]
Can it be useful?

**Comment by Razish** [comment]
What do you mean? I think it's fine as is.

**Comment by EpicLoyd** [comment]
something like 
```lua
    LuaRef s = getGlobal(L, "testString");
    LuaRef n = getGlobal(L, "number");
    std::string luaString = s.cast<std::string>();
    int answer = n.cast<int>();
    std::cout << luaString << std::endl;
    std::cout << "And here's our number:" << answer << std::endl;
```

**Comment by Razish** [comment]
Don't need it templated. Probably best to keep it as is. Could add more helper functions, but I don't know what really needs it.

**Comment by ensiform** [comment]
Luabind would be nice

**Comment by Razish** [comment]
Not sure. Existing implementation works, LuaBind seems more related to binding data between C++ classes and Lua.

**Comment by Razish** [comment]
I think it's best to keep it as is, and provide more helper functions as needed.
