### ISSUE TITLE
Multithreading and lua coroutines

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#319]
Should be possible, when use openjk api ( not syscalls )

**Comment by Razish** [comment]
I'm not sure, doesn't the engine still keep track of the last VM it called into? I recall the renderer asking for that info.

**Comment by EpicLoyd** [comment]
if i implement it... it will be only in serverside. Serverside haven't any renderer, isn't it?

**Comment by Razish** [comment]
The dedicated server still has a "renderer" for silly reasons.

**Comment by EpicLoyd** [comment]
so, lua should be compiled as C++ code for using std libraries
