### ISSUE TITLE
Lua GetFileList reads files from the My Documents/My Games

### ISSUE THREAD

**Issue by keyten** [Razish/japp#320]
And can't read files from the base folder (or japlus folder or etc)

**Comment by Razish** [comment]
Can you show usage code for testing?

**Comment by ensiform** [comment]
Explain further? Literally that folder or just the home path?

**Comment by EpicLoyd** [comment]
+set fs_homepath "."?

**Comment by keyten** [comment]
I use OpenJK.

![docs](http://i.imgur.com/UasLhHD.png)

I found a way to read effects folder, but:
GetFileList('effects', 'efx') -- returns his folder in effects to each file in effects/*/*...
Example:
```
list = GetFileList('effects', 'efx')
list[1] -- 'env', for env/fire.efx
list[2] -- 'env', for env/small_fire.efx
list[3] -- 'env', for env/small_fire_red.efx
...
list[50] -- 'blaster', for blaster/shot.efx
```

If I want to get folders list in effects, I use something like this:
```
local function exists(object, value)
	for _, v in pairs(object) do
		if v == value then
			return true
		end
	end
	return false
end

local list = GetFileList('effects', 'efx')
local models = {}
for _, v in pairs(list) do
	if not exists(models, v) then
		models[#models + 1] = v
	end
end
```

And I can't read the root folder (where is effects, models, maps folders).

**Comment by keyten** [comment]
Yes, I tried to set fs_homepath ".", but... why?
![why](http://i.imgur.com/CC2Dqge.png)

**Comment by EpicLoyd** [comment]
GetFileList('effects/','.efx' )
18 июля 2015 г. 19:12 пользователь "Dmitriy" <notifications@github.com>
написал:
>
> I use OpenJK.
>
> I found a way to read effects folder, but:
> GetFileList('effects', 'efx') -- returns his folder in effects to each
file in effects//...

**Comment by keyten** [comment]
Is it a bug?
![Is it a bug](http://i.imgur.com/ixfcaWU.png)

**Comment by ensiform** [comment]
Its possible that the Lua GetFileList isn't handling the output from the engine correctly.  I'd have to look at @EpicLoyd's code though

**Comment by EpicLoyd** [comment]
i think i fixed it...
