### ISSUE TITLE
What about player camera api?

### ISSUE THREAD

**Issue by keyten** [Razish/japp#322]
For example:
```
local player = GetPlayer( 0 )
player.camera.activate()
player.camera.position = Vector3( x, y, z )
player.camera.angles = Vector3( x, y, z )
-- and player.camera.deactivate()
```

**Comment by EpicLoyd** [comment]
can you explain each function in your example?

**Comment by keyten** [comment]
Of course.

I mean server api (is it possible?). On the client I can change cvars, but I want to manipulate player's camera from server.

player.camera -- special camera (not attached to player).
player.camera.activate -- activates special camera instead of main.

For example:
```
player1.camera.activate()
function MainLoop()
 player1.camera.position = player2.position
 player1.camera.angles = player2.angles
end
```
-- allows player1 to see everything player2 sees (like in spectator).

Or:
```
AddClientCommand('cameraset', function(ply)
 ply.camera.position = ply.position
 ply.camera.angles = ply.angles
end)
AddClientCommand('cameraview', function(ply)
 ply.camera.activate()
end)
-- and 'cameradeactivate'
```
-- allows any player to set a camera in any place and watch it.

**Comment by Razish** [comment]
Can't be done, client decides for itself where to place the camera.

**Comment by EpicLoyd** [comment]
^

**Comment by keyten** [comment]
:(
