### ISSUE TITLE
Kill/event feed

### ISSUE THREAD

**Issue by ensiform** [Razish/japp#339]
Would be nice to have a kill/event feed that is separate from the top notification console.  Preferably with icon support.  I'm sure there's plenty of artists to make death icons and event icons on jkhub.

**Comment by Razish** [comment]
Yep, I just added the client-side death event so I could make this as a lua plugin :p

**Comment by EpicLoyd** [comment]
what events?

**Comment by ensiform** [comment]
I would imagine anything score related. Flag events.

**Comment by Razish** [comment]
Flag captures in CTF, taking the lead, siege objective completion, players connecting/disconnecting
Anything like that, a way to optionally receive those events - some of them are missing and they'd be cool to show on a nice notification popup/feed, with cool modern graphics. Something like TF2 style

**Comment by EpicLoyd** [comment]
Done kill feed. now it requires only icons

**Comment by EpicLoyd** [comment]
done there: https://jkhub.org/topic/7887-pluginclientkill-feed/
