### ISSUE TITLE
Fix: Visuals menu has some overlapping going on

### ISSUE THREAD

**Issue by ensiform** [Razish/japp#340]
Saber trail, saber glow width, and saber core width have issues in the list there plus the tooltip rendering.

![shot2015-10-18_12-35-33](https://github-cloud.s3.amazonaws.com/assets/997399/10565395/e931684a-7594-11e5-8a9b-fc401cfd4bae.jpg)

May need to be moved to assets repo?

**Comment by Razish** [comment]
Those menus are so many years out of date, a lot of the cvars don't exist or have been renamed. See https://github.com/Razish/japp-assets/issues/1

**Comment by Razish** [comment]
All better now Razish/japp-assets@3f9afa4
