### ISSUE TITLE
Awesomium Engine

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#341]
Replace loading screen with preloaded page. Example :Garry's mod

**Comment by ensiform** [comment]
And garry's mod takes like 800 years to load because of it.

Why would you add a html engine just for the load screen.  It would only work with static pages anyway.

**Comment by Razish** [comment]
Not really, server could specify a URL to visit.
I don't plan on implementing this. It's unnecessary, often annoying content that introduces attack vectors.

Something should be done about loading screens, but I'm not sure what. If interactivity should be added, it's not impossible to add to the existing UI.

**Comment by ensiform** [comment]
Actually it is, considering the engine gives up input during loading.

**Comment by EpicLoyd** [comment]
may be use awesomium as ui render?

**Comment by ensiform** [comment]
The engine would need to be able to support it.

**Comment by EpicLoyd** [comment]
Couldn't be done because of engine
