### ISSUE TITLE
Crosshair disappears when pointing at bmodel entities

### ISSUE THREAD

**Issue by ensiform** [Razish/japp#342]
Place to check: any map with doors like mp/ctf2

Doesn't happen in OJK.  Not sure if related to xcvar code I didn't check non-xcvar branch. *soz*

**Comment by ensiform** [comment]
Can someone confirm this happens in master branch?

**Comment by EpicLoyd** [comment]
not related to xcvar code, happens in master

**Comment by EpicLoyd** [comment]
blah, crossfire doesn't draw because there no colour for bmodels

**Comment by ensiform** [comment]
Huh?  It works fine in base as default color/alpha...

**Comment by EpicLoyd** [comment]
OpenJK initializes structure fully: ```vec4_t		ecolor = {0,0,0,0};```
