### ISSUE TITLE
Create standalone msvc (2013/2015) project

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#348]

**Comment by Razish** [comment]
Why standalone? You can still use MSVC as your IDE but use either gcc or MSVC as your compiler.
Why maintain two (or more) separate project files?

**Comment by EpicLoyd** [comment]
if you can setup msvc to use gcc||msvc then...

**Comment by ensiform** [comment]
Proper preprocessor intellisense would be nice regardless of how you "feel" about it.  Its pain in the ass when it shows 90% of the project as not valid.

**Comment by Razish** [comment]
MSVC's approach to intellisense has always derped out when a file is included in multiple projects. You can hint which tokens are defined but it will won't behave great.
A [ctags](https://en.wikipedia.org/wiki/Ctags#Editors_that_support_ctags)/contextual completion engine used by most IDEs works great.

**Comment by ensiform** [comment]
Uhm, there's a pulldown that helps with that.  Still you've made it worse by not even allowing that to work.

**Comment by Razish** [comment]
I haven't changed the behavior of the IDE at all. My recent changes only defaulted to gcc being the default toolset, all the IDE knows is to invoke scons as the build command.
My working copy has better support for building with MSVC's toolset, but the ugliness of the MSVC build environment is getting in the way WRT 32/64 bit. We also have to sort out library compatibility.
gcc will still be the default toolset - it's easier to obtain and run (also *much* smaller) and I want my upcoming Windows builder to produce 32 and 64 bit binaries with ease. I also don't want to have to maintain two separate configurations of compiler switches.
Again, this has nothing to do with using MSVC as the IDE, only the toolset (compiler, librarian, linker, assembler)

> there's a pulldown that helps with that.

Yeah.
> You can hint which tokens are defined but it will won't behave great.

**Comment by ensiform** [comment]
Yes I got that part, its stupid as all hell and you have to keep changing it.

**Comment by Razish** [comment]
Related: Upcoming VS2015 patch allows adding a folder to project, rather than adding each file separately

**Comment by EpicLoyd** [comment]
Closed due to 9f1ad9b7566d5cc0bb676406ff02a6e0d951cb96.
