### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by Morabis** [Razish/japp#350]
I just updated the server side build of JA++ for my clan which wasn't done since april and I encountered a few bugs. 

- When I spawn an npc ship e.g. z-95 and I'm trying to get into the ship I got disconnected with this error:

"invalid playerState field count"

This error message can be found here:

https://github.com/JACoders/OpenJK/blob/d455743cd7b3584b4a131f79fb758250f206c444/codemp/qcommon/msg.cpp#L2367

- Several emotes are not working.

  - amdie1 doesn't play any animation
  - amhiltthrow1 and amhiltthrow2 gives error that the command doesn't exist
  - amsleep gives error: 'insufficient privileges', due to having the admin command with same name

- Admin commands
Now with the new admin strings system (for me it's new) whenever an admin is using a command it get announced to everyone on the server.

**Comment by EpicLoyd** [comment]
first "invalid playerState field count" probably because of network mismatch ( optimized vehicle networking )

**Comment by ensiform** [comment]
Is the server and client OpenJK newer than September 29th?

**Comment by Morabis** [comment]
Yeah after updating my client OpenJK it works properly.

**Comment by Morabis** [comment]
I fixed the mentioned emotes on my build. Do you want me to make a pull request of it?

**Comment by EpicLoyd** [comment]
ya

**Comment by EpicLoyd** [comment]
fixed all bugs
