### ISSUE TITLE
Amkick bug

### ISSUE THREAD

**Issue by Morabis** [Razish/japp#354]
I just compiled a linux build to try on my server and encountered an interesting bug. Whenever I try to use the amkick command the server simply restarts. There are no traces in logs of what have happened. It doesn't even log the usage of amkick command. 
I would say this bug is there since the 23th of November or later as builds before that were working without this issue.

**Comment by Razish** [comment]
Confirmed. Was due to the new admin prints, assuming that it could print to a client that's about to be kicked/banned (in which case `NULL` was being passed for the entity.

Fix incoming
