### ISSUE TITLE
Bad animation bug

### ISSUE THREAD

**Issue by Morabis** [Razish/japp#356]
My people in EFF reported that after i updated Ja++ on our servers sometimes players got disconnected with an animation error:

Bad animation number: 1963

On time when I tried to connect to the server I also got this error and couldn't enter. I found this error in the code here:

https://github.com/Razish/japp/blob/38738284a54cdfd4df97314dfda4879138004430/cgame/cg_players.cpp#L2072

So I would say it's something with emotes? I have no idea what animation can have that number.

**Comment by ensiform** [comment]
Likely they need to update client side too?

**Comment by Morabis** [comment]
I have an updated client and I got this error once when I tried to go to server. Once I restarted it the error gone away. We tried to find out what causes it but no luck it seems to happen randomly.

**Comment by EpicLoyd** [comment]
give us stack trace please if you can

**Comment by Morabis** [comment]
We figured out what is causing the trouble. It's the spinkick when used with staff saber. As default spinkick is meant to use with melee but staff also has kick on secondary attack button so its possible to make a spinkick with staff. Although when you try to make it you get disconnected and also all those players who have seen you meanwhile. I think the error is happening because of the spinkick it's too much animation in one frame with the regular staff kick.

**Comment by EpicLoyd** [comment]
spin kick it is.....?

**Comment by Morabis** [comment]
Roundhouse kick, when you are in melee and you kick with your leg while turning around.

**Comment by JokerMaster** [comment]
i have kind the same Problem wen im using The Red Stance (Single Saber) and Perform that Kick the Particles just stay and cause the game to crash after 1 or sometimes 2 times doing that move 
![shot2015-12-12_11-18-32](https://cloud.githubusercontent.com/assets/16265946/11761422/55f5bd5c-a0c2-11e5-9593-b28a340d71a0.png)
![shot2015-12-12_11-18-46](https://cloud.githubusercontent.com/assets/16265946/11761423/577d138c-a0c2-11e5-9016-1fb00d498e20.png)

**Comment by EpicLoyd** [comment]
@JokerMaster its my fault probably...related to localents code >,>

**Comment by Razish** [comment]
@JokerMaster can you confirm if this happens on latest revision on Windows? I have not been able to reproduce it on Linux for a week or two. If it does, feel free to create a new issue.

Did some basic investigation of this issue, couldn't see where it was getting that absurd animation number. Seems like a translation error between `LS_` and `BOTH_` enums.

**Comment by JokerMaster** [comment]
Yes this happens on Windows with the latest version and i all ready reinstall but still same problem no difference between OpenJk or not.

**Comment by Razish** [comment]
I meant specifically the latest git revision, not the latest version available on the site. It would require compiling it yourself.
Could you give me the output of `clientinfo` when connected to a server and the bug occurs for your own saber trail?

**Comment by JokerMaster** [comment]
well im not an expert but i hope i got it right. The Saber Trail bug can be forced by anyone on the server wen he does this move. i dont need to see him for that. (without openjk the frame rate goes down to 20 or Crash the game)
![shot2015-12-13_15-14-32](https://cloud.githubusercontent.com/assets/16265946/11767401/a7e854e0-a1ac-11e5-85a6-cd78e1bcf67b.png)
