### ISSUE TITLE
amweather crashes OpenJK dedicated server

### ISSUE THREAD

**Issue by danyul0w0** [Razish/japp#357]
When using any of the amweather commands on an OpenJK Dedicated server it crashes the dedicated session with a Windows error, normal game stays up fine.

Error in server window:

terminate called after throwing an instance of 'std::out_of_range' what(): basic_string::replace: __pos (which is 4294967295) > this->size() (which is 0)

Then the application requests runtime termination.

**Comment by ensiform** [comment]
O.o and where is this string located?

**Comment by danyul0w0** [comment]
It happens immediately after running any amweather effect command in the server console, it's the last thing printed before it force closes.

**Comment by ensiform** [comment]
Are you running it as a client connected or as the server?  And within where does AM_Weather function in g_admin.cpp get to before it crashes if at all?

**Comment by ensiform** [comment]
I'm betting its related to AM_DrawString(ADMIN_STRING_WEATHER, ent, cmd); as that uses std::strings

**Comment by danyul0w0** [comment]
It's ran as an admin client which then creates the server crash shutdown immediately after entering. Regarding the g_admin.cpp, I have no idea.

**Comment by ensiform** [comment]
Stack trace will be required to see the problem :/

**Comment by danyul0w0** [comment]
Ah unfortunately I don't know how to do that :[

**Comment by ensiform** [comment]
Are you using a specific build or compiled self?

**Comment by danyul0w0** [comment]
It's the Windows server build and client build on the japp.jkhub page

**Comment by ensiform** [comment]
Those are quite possibly outdated a while? @Razish

**Comment by danyul0w0** [comment]
Attached an image of the dedicated server console here: http://i.imgur.com/x18ToDv.png

**Comment by ensiform** [comment]
Likely means a failure is happening here. https://github.com/Razish/japp/blob/master/game/g_admin.cpp#L265-L266

**Comment by danyul0w0** [comment]
An update, same crash message appears in dedicated console after using amkick on bots. Latest Windows client (Dec 17th)

**Comment by Blackwolf1337** [comment]
I think we can close this down, I tried both /amkick on bots per Server Panel and /amweather also, no crashes at all. Try using different OpenJK builds or compile it by yourself.

**Comment by EpicLoyd** [comment]
is it shows messages properly?

**Comment by Blackwolf1337** [comment]
If you use /amweather on the Serverpanel it won't show any announcement, but that can be fixed. On the clientside it works fine when using it.
![unbenannt](https://cloud.githubusercontent.com/assets/17799512/14022533/87bace62-f1e0-11e5-9143-8d7457671455.png)

**Comment by EpicLoyd** [comment]
just checked it. Closing
