### ISSUE TITLE
How to use Mysql/sqlite in ja++?

### ISSUE THREAD

**Issue by Dexter4637** [Razish/japp#363]
@EpicLoyd can u tell me how to use mysql/sqlite with ja++? I cant compile it under linux with `no_mysql=0`. Maybe u can help.

**Comment by EpicLoyd** [comment]
as far as i can remember japp builds fine under linux and have some errors on windows. What error do you get?

**Comment by Razish** [comment]
I will experiment with SQL/sqlite support on Linux soon, where soon is an undetermined point in time before I die.

**Comment by Dexter4637** [comment]
When I try to compile with "scons no_sse=1 no_mysql=0" i get this error: usr/bin/ld: connot find -lmysqlclietn

**Comment by Dexter4637** [comment]
push, no ideas @EpicLoyd ?

**Comment by EpicLoyd** [comment]
uh oh, seems to me that compilator cannot find static mysql library

**Comment by EpicLoyd** [comment]
mm...in libs/linux/32(64)/ lib called libmysqlclient.a  not mysqlclient.a
