### ISSUE TITLE
amnotarget

### ISSUE THREAD

**Issue by Arcadiaprime** [Razish/japp#377]
Recently, /amnotarget was added to the list of admin commands, however there is no physical way to use it without the bit-field calculator being updated on the site to generate the field needed for admins to use it.

**Comment by ensiform** [comment]
Unless you just figure out which bit comes next and figure it out with math :p

**Comment by Arcadiaprime** [comment]
I'm no good with the technical stuff.

**Comment by Blackwolf1337** [comment]
I'll create a standalone bitcalculator.


Von Outlook auf Android gesendet






On Wed, Apr 6, 2016 at 10:10 PM -0700, "Arcadiaprime" <notifications@github.com> wrote:





I'm no good with the technical stuff.

---

**Comment by Razish** [comment]
The calculator on the site [i]is[/i] standalone, just open the .html page locally.
We just need to change https://github.com/Razish/japp-site/blob/master/calculator.html#L261-L291

**Comment by Arcadiaprime** [comment]
I was talking about this one for admin permissions: http://japp.jkhub.org/calculator.html

**Comment by Blackwolf1337** [comment]
@Razish Didn't knew that you've published the calculator :sweat_smile:

@Arcadiaprime as razish said just download the html and edit it.

**Comment by Razish** [comment]
> I was talking about this one for admin permissions: http://japp.jkhub.org/calculator.html

Yep, it's the same page. I've put the whole site on github so any contributor can fix it up

**Comment by Blackwolf1337** [comment]
@Razish I'll take care of it tomorrow, if I got time.

**Comment by Razish** [comment]
Fixed in Razish/japp-site@93f32e5

**Comment by Arcadiaprime** [comment]
I still don't understand how that works.

**Comment by Blackwolf1337** [comment]
You check the fields with permission copy the number and then add them with adminadd into the <privileges> field in JKA.

**Comment by Blackwolf1337** [comment]
Can you explain your problem... What do you not understand?

**Comment by Arcadiaprime** [comment]
It was updated at some point today so the issue was solved.
