### ISSUE TITLE
C++fying code

### ISSUE THREAD

**Issue by EpicLoyd** [Razish/japp#378]
classes instead of structures, namespaces and so on

**Comment by ensiform** [comment]
You don't really need to get too carried away.  C++ for the sake of c++ doesn't make a whole lot of sense.

**Comment by Blackwolf1337** [comment]
Why... ?

**Comment by ensiform** [comment]
Why do it or why it doesn't make sense?

**Comment by Razish** [comment]
No plans for a C++/OOP rewrite for the sake of it. C++/OOP style code will be written where necessary, leaving the majority of the code as is.
