### ISSUE TITLE
g_weaponDisable should remove ammo pickups

### ISSUE THREAD

**Issue by Razish** [Razish/japp#395]
issue seems related to trip mines etc being ammo_ entities

**Comment by ensiform** [comment]
It's actually related to checking for sabers only.

If you still allow melee and turrets then it's not technically saber only.  It should be smart enough to disable ammo if all weapons that use an ammo type are disabled.

**Comment by Razish** [comment]
> disable ammo if all weapons that use an ammo type are disabled

Agreed. It could be done on a per ammo type basis so it only keeps around the relevant ammo pickups.

**Comment by ensiform** [comment]
May want to still improve the saber only early out so it doesn't have to do even more checks for per ammo, though.

**Comment by Razish** [comment]
Not a performance issue, the check for spawning pickups only need to be done once.
