### ISSUE TITLE
amdropsaber

### ISSUE THREAD

**Issue by danyul0w0** [Razish/japp#397]
Currently amdropsaber duplicates the saber model rather than dropping the one in the players hand, I have also noticed that sometimes this causes animations to become stuck after doing a jump, wherein you will kind of float around the floor with a bugged sideways walking animation until the 'dropped' saber disappears.

**Comment by Razish** [comment]
Server? Client?
There is a known issue with grapple prediction and dropped sabers. Try `cg_predictGrapple 0` if you're using JA++ client on a JA+ server and seeing issues.

**Comment by danyul0w0** [comment]
JA++ server and client, latest version.
