### ISSUE TITLE
flipkicking protected players

### ISSUE THREAD

**Issue by Razish** [Razish/japp#400]
should not be able to do :>

**Comment by EpicLoyd** [comment]
how players are protecting?what bug?

**Comment by ensiform** [comment]
I assume dueling immunity?

**Comment by Razish** [comment]
amprotect, probably AFK invulnerability too.

**Comment by Wookiee-** [comment]
I tested this on my server when I amprotected a friend of mine and was able to flipkick knocking him back.

**Comment by Razish** [comment]
Fixed.
