### ISSUE TITLE
Siege / Vehicle Bug

### ISSUE THREAD

**Issue by danyul0w0** [Razish/japp#401]
Something is causing the ATST vehicle to get locked from aiming upwards, preventing the Hoth siege part with the ATST from being possible. You can aim up when you first enter the vehicle and then it is instantly locked to forward or down. Speed of the ATST secondary fire is also incredibly fast.

**Comment by ensiform** [comment]
Probably related to razor's vector changes in ja++ ?

@Razish

**Comment by FirePhoenix303** [comment]
Yeah it's the same with all walker- type vehicles

**Comment by Razish** [comment]
I just compared alt-fire in atst_vehicle between OpenJK and JA++, it's identical here.
