### ISSUE TITLE
FullForce duel problem

### ISSUE THREAD

**Issue by Ekzi** [Razish/japp#407]
Hello! What command for fullforce duel challenge?
engage_fullforceduel not work.

**Comment by Razish** [comment]
It's `engageduelff`
Leaving this issue open because it should match JA+'s command.

**Comment by mairontai** [comment]
hi. I used this command, but the duel is still without force, only lightsaber. 
how does it work?

**Comment by ensiform** [comment]
The server needs to have the option enabled for it to work I believe.
