### ISSUE TITLE
Fix: Allow serverside to disable side kicks

### ISSUE THREAD

**Issue by srcanseco** [Razish/japp#411]
As an optional Cvar. Also, this should be set as a default setting, since this is how base behave.

**Comment by Wookiee-** [comment]
Added a fix from jaPRO this is it here https://github.com/Wookiee-/japp/commit/ba519df6ed77ea511b5bbeec77aa325455bc59ed

**Comment by Exmirai** [comment]
Assume that was fixed long time ago
