### ISSUE TITLE
Add @mentions to chat

### ISSUE THREAD

**Issue by Exmirai** [Razish/japp#418]
Also notify player if smb mentioned him and game was minimized

**Comment by ensiform** [comment]
Do you have a way to detect if their game was minimized from mod?

**Comment by Exmirai** [comment]
Think it is possible

**Comment by Razish** [comment]
Related:
* Desktop notification support added for Linux clients in 208b00e
* Support JPLua plugin at Razish/japp-assets@dc1a5d5

**Comment by Exmirai** [comment]
Implemented in dc1a5d5f1a594bbd3ce2124e7ff46197ac4bc992
