### ISSUE TITLE
Building failing for x86

### ISSUE THREAD

**Issue by azurda** [Razish/japp#431]
Been trying to get this to work but no success so far, I tried running Ubuntu-server and now debian 

Current build settings

`NO_SSE=1 scons force32=1 no_notify=1 no_sql=1`

scons: Reading SConscript files ...
Building 3961116 using 1 threads
	host: Linux
	target: Linux forced 32bit
	C compiler: gcc 4.9.2
	C++ compiler: g++ 4.9.2
	python: 2.7.9 at /usr/bin/python
	scons: 2.3.1
options:
	configuration: release
	instruction set: i386 with x87 fpu
	sql support: disabled
	notify support: disabled
	crash logging: enabled
	geoip support: enabled

So, initially I was getting errors related to instructions

```
/usr/include/bits/mathinline.h:747: Error: no such instruction: `movzwl WORD PTR 86[esp],eax'
/usr/include/bits/mathinline.h:748: Error: no such instruction: `andl $0xf3ff,eax'
/usr/include/bits/mathinline.h:749: Error: no such instruction: `orl $0x0400,eax'
```

So far managed to get pass this problem by changing the SCons CFLAGS(https://github.com/Razish/japp/blob/master/SConstruct#L335-L338) flags in NO_SSE, adding

`-S -masm=intel`

but right afterwards I'm getting a new error 
```
linking: cgamei386.so
cJSON/build/release/gcc/32/cgame/libcJSON.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
scons: *** [cgamei386.so] Error 1
scons: building terminated because of errors.
```

the file cJSON.o says its ASCII and invalid format... any hints? 

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

**Comment by Razish** [comment]
Closing this to clean up old issues. Only Debian 10+ is currently supported. Please open a new issue if current `master` doesn't compile for you.
