### ISSUE TITLE
Can't register commands through JPLua without a plugin

### ISSUE THREAD

**Issue by Razish** [Razish/japp#62]
```
]/lua AddConsoleCommand( 'test' function( args ) end )
```

particularly without any plugins installed, this will crash because JPLua.currentPlugin is NULL

**Comment by EpicLoyd** [comment]
Is it necessary to assign commands to plugin?

**Comment by EpicLoyd** [comment]
Closed in 5ae5d53a96b6916f4d8100f48042d27b72a0dc1e
